### ISSUE TITLE
Axios throws "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by zourtney** [sormy/webpack-fix-default-import-plugin#1]
I'm getting a strange error when attempting to use [Axios](https://github.com/mzabriskie/axios) alongside this webpack plugin. I dug around both projects a little, but didn't find any obvious reasons. I suspect it has to do with how they've chosen to export the library:

```typescript
import axios from 'axios';   // <-- supported WITHOUT this webpack plugin
```

Attempting to use it:

```typescript
axios.get('/anything');
```

...results in:

```
app.bundle.js:836 Uncaught RangeError: Maximum call stack size exceeded
    at assignValue (app.bundle.js:836)
    at forEach (app.bundle.js:811)
    at merge (app.bundle.js:845)
    at assignValue (app.bundle.js:838)
    at forEach (app.bundle.js:811)
    at merge (app.bundle.js:845)
    at assignValue (app.bundle.js:838)
    at forEach (app.bundle.js:811)
    at merge (app.bundle.js:845)
    at assignValue (app.bundle.js:838)
```

I've created a repo with a minimal code sample:
https://github.com/zourtney/webpack-fix-default-import-axios

**Comment by sormy** [comment]
thanks for good reproduce case, looking on it

**Comment by sormy** [comment]
try v1.0.2

**Comment by zourtney** [comment]
Thanks for the quick turnaround! My preliminary testing shows that it is now functional 👍, but may generate warnings -- depending on the libs included.

For example, a bare-bones React app will throw:

```
Warning: Accessing PropTypes via the main React package is deprecated.
Use the prop-types package from npm instead.
```

From code:

```typescript
import React from 'react';
import ReactDOM from 'react-dom';

ReactDOM.render(
  React.createElement('div', null, 'hello world'),
  document.getElementById('app'),
);
```

It appears to originate from a custom `React.PropTypes` getter, which plugin `v1.0.2` now iterates over:

```javascript
Object.defineProperty(React, 'PropTypes', {
  get: function () {
    /* throw warning... */
  }
});
```

Probably harmless, but let me know if you have any clever ideas here.

**Comment by sormy** [comment]
the problem actually in axios defaults.js. Blindly adding default to exports is not safe for this module. I'm going to revert code back but will put workaround. It could be perfect if axios team could change logic to not rely on exported default or to put more unique export property like module.exports.__isAxios  which could be used for better identification

**Comment by zourtney** [comment]
Confirmed, `1.0.3` is working well. I figured it had something to do with how Axios was exporting, but wasn't sure on the details. Thanks for digging in it!
