### ISSUE TITLE
Deprecate the plugin in favor of using --esModuleInterop compiler option

### ISSUE THREAD

**Issue by tomaskikutis** [sormy/webpack-fix-default-import-plugin#5]
I've spent a few hours trying to fix this plugin without noticing that there's a compiler option doing the same thing.

To be clear, this plugin does work for >90% of cases, but I bumped into one where it didn't work. Enzyme uses `domutils` and it [requires and binds it's own functions](https://github.com/fb55/domutils/blob/master/index.js#L12) when exporting. It's not a problem with `domutils` library, but with how this plugin works - that is by injecting defaults everywhere instead of generating import helpers like the TypeScript compiler option does.

[esModuleInterop](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop) is available since TypeScript 2.7

**Comment by sormy** [comment]
It is good that MS finally fixed the issue on TS level. Thank you for information, I will update README and deprecate the plugin ;-)
